# Generated by Django 5.2 on 2025-05-01 13:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
import pgvector.django
from pgvector.django import VectorExtension
MISTRAL_EMBEDDING_DIM = 1024


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcripts', '0003_transcript_title'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='transcripts.transcript')),
            ],
            options={
                'verbose_name': 'Text Chunk',
                'verbose_name_plural': 'Text Chunks',
                'ordering': ['transcript', 'created_at'],
                'indexes': [models.Index(fields=['transcript'], name='chatbot_tex_transcr_e709b5_idx')],
            },
        ),
    ]
