# Generated by Django 5.2 on 2025-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
