# Generated by Django 5.2 on 2025-04-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='The raw text content of the meeting transcript.')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='The current status of the AI processing workflow.', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Stores any error message if processing failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transcript record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transcript record was last updated.')),
                ('meeting', models.ForeignKey(help_text='The meeting this transcript belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
