# Generated by Django 5.2 on 2025-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_transcript_async_task_id_transcript_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
