# Generated by Django 5.2 on 2025-04-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analysis', serialize=False, to='transcripts.transcript')),
                ('summary', models.TextField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list, help_text="A list of key points extracted from the transcript, e.g., ['Point A', 'Point B'].", null=True)),
                ('action_items', models.JSONField(blank=True, default=list, help_text="List of action items, e.g., [{'task': 'Send meeting notes', 'responsible': 'Alice', 'deadline': 'YYYY-MM-DD'}]", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
