# Generated by Django 5.2 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='action_items',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='task',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
